import "./globals.css";
import Navbar from "@/src/components/Navbar";
import { Montserrat } from "next/font/google"

export const metadata = {
  title: "Execirse Next.js",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  weight: ["300", "400", "500", "600"],
  style: ["italic", "normal"],
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navbar />
        <main className="container mx-auto h-[calc(100vh-3rem)] flex justify-center items-center">
          {children}
        </main>
      </body>
    </html>
  );
}
